### ISSUE TITLE
lofreq_star-2.1.5_linux-x86-64 : ./lofreq: error while loading shared libraries: libhts.so.3

### ISSUE THREAD

**Issue by HagenC** [CSB5/lofreq#111]
According to your blog the installation is simple:

"Installation from Binary Packages
Download the binary LoFreq distribution matching your system (e.g. Linux or MacOSX) from the dist folder on Github and unpack it. LoFreq can then simply be called with ./lofreq_star-2.1.0/bin/lofreq (assuming you downloaded version 2.1.0). You can move the folder anywhere you like (just preserve its structure) or copy its contents to a system-wide installation path, e.g. /usr/local

cp -rv ./lofreq_star-2.1.0/* /usr/local/"

However running ./lofreq  from gives the following error message: ./lofreq: error while loading shared libraries: libhts.so.3: cannot open shared object file: No such file or directory.

What does that mean and how can I solve it? 
Thanks.

**Comment by andreas-wilm** [comment]
Hi there,

I think I forgot to hardlink the release binary against libhts. You will
either need to install libhts separately or even easier: install LoFreq via
Bioconda (or Brew of you are on a  Mac).

Best,
Andreas

**Comment by HagenC** [comment]
Thanks for the fast reply. Installed using Bioconda.

**Comment by siyangxia** [comment]
Hi I am wondering if there is any updates regarding this error? I am installing lofreq v2.1.5 on Docker and encountered the same error. I confirmed the htslib location and libhts.so.3 is soft linked to libhts.so.1.15.1. Unfortunately due to environment conflict I cannot install it through bioconda, so I am wondering if you could give me some suggestions on how to fix this error. Thank you!
