### ISSUE TITLE
installing optional tools

### ISSUE THREAD

**Issue by igordot** [CSB5/lofreq#23]
I was able to download the binary. However, I wanted to use the optional tools as well. It looks like the only way to get them is by downloading the source. I did that. I copied them to a location in my $PATH. However, when I run `lofreq vcfplot` or `lofreq2_vcfplot.py`, I get:

```
FATAL: Couldn't find LoFreq modules. Are you sure your PYTHONPATH is set correctly?
```

I also tried navigating to `lofreq-2.1.2/src/tools` and running `python setup.py install`, but then I get an error:

```
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import setup_conf
ImportError: No module named setup_conf
```

How do I get setup_conf?

Is there a better way to install optional tools?

**Comment by andreas-wilm** [comment]
Hi,

the precompiled packages do include the "tools" (at least for versions >= 2.1). These are really just the following three scripts:

- `lofreq2_cluster.py`
- `lofreq2_indel_ovlp.py`
- `lofreq2_vcfplot.py`
 
With the exception of the stand-alone `lofreq2_indel_ovlp.py`, they depend on also installed LoFreq Python packages and matplotlib+numpy in case of `lofreq2_vcfplot.py`.

The should be located in the directory into which the `lofreq` binary was installed. If you can call `lofreq` you should therefore also be able to use any of the above. Could you please check?

Thanks,
Andreas

**Comment by igordot** [comment]
I downloaded lofreq_star-2.1.2_linux-x86-64.tgz and it only contains the bin directory with the 3 main files (lofreq, lofreq2_call_pparallel.py, and lofreq2_somatic.py).

**Comment by andreas-wilm** [comment]
You're right. I mistakenly checked pre-installed source packages and they do by default come with those tools. The binary packages don't. So, to answer your original question: to get the tools installed properly, you will have to install the source package. The exception is `lofreq2_indel_ovlp.py` which you could just download (https://github.com/CSB5/lofreq/raw/master/src/tools/scripts/lofreq2_indel_ovlp.py) and run (with Python 2.7 or make executable first) because it's independent of any libraries.

Andreas

**Comment by igordot** [comment]
I tried installing them using `python setup.py install`, but I got an error. See my original post.

**Comment by andreas-wilm** [comment]
To install from source you have to download the source package itself and install everything with `configure` and `make install`.

**Comment by schizobean** [comment]
Hi Andreas,

I ran in the same issue as igordot and I fixed it partially by installing from source like you suggested. I say partially because while `lofreq vcfplot` works fine now, `lofreq cluster` still does not work. It gives the following error: `"Couldn't import any of LoFreq SNP format modules"`.

Looking at the `lofreq2_cluster.py` script, it seems like there is an issue finding the "lofreq" and "lofreq2_local" modules. Do they even exist in the 2.1.2 version? If they do, what could be my problem?

Thanks a lot!

**Comment by andreas-wilm** [comment]
Hi Schizobean,

if you're running `lofreq` straight out of its source directory (assuming you downloaded the source tarball or cloned the git repo) this should always work.

If you installed LoFreq into a non-default directory, you should have gotten a message during installation telling you to adjust your `PYTHONPATH`.

To troubleshoot this, could you please provide output for the following commands

     which lofreq;
     echo $PYTHONPATH;

Thanks,
Andreas

**Comment by schizobean** [comment]
Thanks for your quick reply!

I am running LoFreq from the source tarball. I did get the `PYTHONPATH` message after installation for the vcfplot command. I added this path `/Users/Alex/prog/lofreq_source_2.1.2/lib/python2.7/site-packages` to the `PYTHONPATH` and vcfplot started to work.

Here is what you requested:

`which lofreq`
/usr/local/bin/lofreq
`echo $PYTHONPATH`
:/Users/Alex/anaconda/pkgs:/Users/Alex/prog/lofreq_source_2.1.2/lib/python2.7/site-packages

Thanks!
Alex

**Comment by andreas-wilm** [comment]
Hi Alex,
does `/Users/Alex/prog/lofreq_source_2.1.2/bin/lofreq cluster` work?

**Comment by schizobean** [comment]
It does not...

`$ /Users/Alex/prog/lofreq_source_2.1.2/bin/lofreq cluster`
Couldn't import any of LoFreq SNP format modules

**Comment by andreas-wilm** [comment]
Okay. It's actually a bit weird that you have two installations and your `PATH` seems to point to one and `PYTHONPATH` to the other. 

What do the following return:

`find /Users/Alex/prog/lofreq_source_2.1.2/ -name \*py `
and
`find /usr/local/lib -name \*py | grep lofreq`
?

Thanks,
Andreas

**Comment by schizobean** [comment]
Maybe it is because I did a default directory install first, but when it did not work, I then tried a non-directory install. Or it has to do with calling the python interpreter from Anaconda but the lofreq packages were not installed under the Anaconda folder tree... Maybe what I am saying does not make technical sense, but I hope you get the gist. :)

`$ find /Users/Alex/prog/lofreq_source_2.1.2/ -name \*py`
/Users/Alex/prog/lofreq_source_2.1.2//bin/lofreq2_call_pparallel.py
/Users/Alex/prog/lofreq_source_2.1.2//bin/lofreq2_cluster.py
/Users/Alex/prog/lofreq_source_2.1.2//bin/lofreq2_indel_ovlp.py
/Users/Alex/prog/lofreq_source_2.1.2//bin/lofreq2_somatic.py
/Users/Alex/prog/lofreq_source_2.1.2//bin/lofreq2_vcfplot.py
/Users/Alex/prog/lofreq_source_2.1.2//lib/python2.7/site-packages/lofreq_star/__init__.py
/Users/Alex/prog/lofreq_source_2.1.2//lib/python2.7/site-packages/lofreq_star/utils.py

`$ find /usr/local/lib -name \*py | grep lofreq`
/usr/local/lib/python2.7/site-packages/lofreq_star/__init__.py
/usr/local/lib/python2.7/site-packages/lofreq_star/utils.py

**Comment by andreas-wilm** [comment]
Okay, now I remember: you will have to install the external pyvcf module: https://github.com/jamescasbon/PyVCF
I scrapped the LoFreq internal one a while ago but forgot to document this.

**Comment by schizobean** [comment]
Well, I did install it. It is within `:/Users/Alex/anaconda/pkgs`, which is in my `PYTHONPATH`. Moreover, I think `lofreq vcfplot`uses the PyVCF module right? And the `vcfplot` command works well.

Anyhow, I will install the "non-Anaconda" PyVCF module today and give it a try... just in case. Will let you know if it works.

**Comment by fifthguy** [comment]
Hi,

I get the following error trying to compile (i want the extra scripts as well and need to compile):

In file included from bam_md_ext.c:38:0:
/home/.../samtools-1.3/bam.h:189:28: error: conflicting types for ‘seq_nt16_int’
 #define bam_nt16_nt4_table seq_nt16_int

I'm using an ubuntu machine (14.*); according to the docs, I have all the pre-req dependencies.

Do you have an idea on how to fix this?

Thanks and best regards!

**Comment by fifthguy** [comment]
Hi, (sorry for the prev. post; just found the workaround)

Similarly to schizobean I also get the error 

Couldn't import any of LoFreq SNP format modules.

I can however import pyvcf (installed through pip), and with the PYTHONPATH pointing towards the pip package-sites

Any ideas, on what could be the issue?

Thanks and best regards!

**Comment by andreas-wilm** [comment]
Yeah, the issue is that the auxiliary tools were more meant for me internal use, rather than the distribution package. If you want to use them nevertheless please just install the pyvcf module. That should do the trick . Thanks

**Comment by fifthguy** [comment]
Hi, 

what I'm saying is that i already have pyVCF (installed thgough pip), should i compile the github version that you've linked or simply make the PYTHONPATH point somewhere else etc.?

Thanks again,

Best!

**Comment by andreas-wilm** [comment]
Oh okay. No need to compile. As long as pyvcf is in your PYTHONPATH things should just work.

**Comment by fifthguy** [comment]
Hi,
I understand that it should, but I am nontheless getting "Couldn't import any of LoFreq SNP format modules.". 

Do you have an idea, what I can do to fix this?

Thanks again, 

best!

**Comment by fifthguy** [comment]
Thanks. Found the problem. (PYTHONPATH wasn't in all of my screen windows). Sorry to bother you

**Comment by andreas-wilm** [comment]
Sorry, seems I'm a bit slow today.

Could you check if this is a version mismatch between the interpreter set in the lofreq scripts (head -n1 on any of the tools) and the one used for pyvcf installation?

Andreas

**Comment by andreas-wilm** [comment]
Okay, even better :)

**Comment by fifthguy** [comment]
Hi 

"Sorry, seems I'm a bit slow today.

Could you check if this is a version mismatch between the interpreter set in the lofreq scripts (head -n1 on any of the tools) and the one used for pyvcf installation?

Andreas"

will check next time it doesn't work... 

Thank you. :)

**Comment by fifthguy** [comment]
Hi A!

I just another question: which clustering algo do you use in lofreq cluster (it's not written in the paper if I recall correctly).

Thanks again, T

**Comment by andreas-wilm** [comment]
It's naive and greedy clustering according to the frequencies: see http://journals.plos.org/plosntds/article?id=10.1371/journal.pntd.0004052
