### ISSUE TITLE
Call variants when the reference is an N

### ISSUE THREAD

**Issue by magicDGS** [CSB5/lofreq#30]
Some flag could be provided for allow calling variants when there is an N in the reference. As we discuss by email, it could be done just replacing the N for a random reference; but it will be very useful for the final user to be allow to output this kind of variants.

Including this in the code could be done by:

* When the reference is an N, replace it by a base that have no coverage in the data. Using a reference with 0 coverage will allow to output any variant that is found. Nevertheless, it could be an issue if each base (ATCG) is in at least one read, so it would not be reported if it is a reference SNP.
* Perform the calling using the replaced N as a reference.
* Change the reference to N again before reporting the variant.

The first point could be change by using the consensus variant approach as in previous versions.

**Comment by magicDGS** [comment]
Another way of doing this is recovering the concept of CONSVAR for variants where the reference is an N. This will be very helpful and easy to implement, although the quality could be tricky to compute.

**Comment by andreas-wilm** [comment]
Older versions actually had a flag that supported to call "variants" on N positions (--dont-skip-n in versions <=2.1.0 but we never used or tested it). At one stage it started interfering with the rest of the code so we removed the option, due to lack of usage and testing. An easy workaround from the user site is to replace any N with a random nucleotide.
