### ISSUE TITLE
what is the default filter?

### ISSUE THREAD

**Issue by map2085** [CSB5/lofreq#67]
Dear Andreas,

Can you please summarize what exactly the default filter applied by `lofreq call` consists of? `lofreq filter` does not provide defaults for each argument.

Does the SNV quality p-value, which is controlled by `-a`, include the strand bias test, or only the quality score calculation which is the core of the LoFreq algorithm? Can you please explain why the `-a 1` option may be needed if one uses `--no-default-filter`?  

Also, what is  `dynamic` Bonferroni correction?

How does `dynamic` Bonferroni correction relate to `--no-default-filter`?

Why is this relevant to the `-l` command for targeted regions?

What is "joinedQ"?

Partial answers to some of these questions are scattered in multiple-responses to questions in the mailing list and on FAQs, but those answers were not comprehensive, sometimes left out details, sometimes referred to older version of Lofreq, etc.

Thank you!

**Comment by aledj2** [comment]
:+1:

**Comment by andreas-wilm** [comment]
Sorry, for the late answer!

The default filter has been a constant source of confusion. And the only reason it's in there, because we wanted to make sure, that people don't forget to filter. That backfired in the long run...

In LoFreq variant qualities are proper p-values and hence you can use multiple testing correction on them and filter based in p-value thresholds (`-a`). The default is 0.01 = Q20 (applied after multiple testing correction, e.g. Bonferroni).

The default behaviour is to filter using multiple testing correction (`--bonf dynamic`) on the variant quality. In addition, default filters are used (coverage of 10 and strand bias filtering using FDR; see `lofreq filter --verbose`). The latter can be switched off by using `--no-defaults`. 

LoFreq is heavily based on the notion of error probabilities. By default it joins mapping quality, base quality and alignment quality (all error probs!) into a joined probability: either the read is wrongly mapped (mapping qual) or if it isn't then the base might be wrongly aligned (alignment qual == BAQ) or if it isn't, then it might still be the wrong base (base qual).  The thus computed joined quality / error probabilty is used as input to the Poisson Binomial core of LoFreq that produces a p-value per variant.  

Using regions ("-l") just makes sure that off-target mappings are not considered during variant calling.

Hope that addresses all questions. We are rewriting LoFreq entirely and will make the internal workings more transparent.

Andreas

**Comment by amunzur** [comment]
Hi Andreas, 

I am wondering if there any updates on this issue, was anything added to the default filters in the past previous years? I too am struggling to fully understand the innerworkings of the default filters.
