### ISSUE TITLE
Strand Bias in unidirectional reads

### ISSUE THREAD

**Issue by abolia** [CSB5/lofreq#77]
Hi, 

We are seeing that Lofreq is filtering out homozygous calls (using the default filter) in unidirectional areas (where all the reads are supporting the variant, no ref).  After applying the -no-default-filter, we see the Homozygous variant in unidirectional area is given SB=2147483647, which looks weird, not sure if its calculating the SB score correctly. Is there a way to call these homozygous variants that are on unidirectional reads, without turning off the filter.

When I run in the debug mode:
"
DEBUG(plp.c|compile_plp_col): Processing 1:5142629
1	5142629	C	G	counts:rv/fw A:0/0 C:0/0 G:180/0 T:0/0 N:0/0 heads:3 tails:1 ins:0 del:0 hrun=1
DEBUG(lofreq_call.c|call_snvs): 1 5142629: passing down 180 quals with noncons_counts (0, 180, 0) to snpcaller(num_snv_tests=3 conf->bonf=3, conf->sig=0.010000)
DEBUG(lofreq_call.c|call_snvs): low freq snp: 1 5142629 G>G pv-prob:1.31177e-639;pv-qual:6388 counts-raw:180/180=1.000000 counts-filt:180/180=1.000000
"
Thanks,
Ashini

**Comment by andreas-wilm** [comment]
Hi Ahsini,

there are a few default filters applied in LoFreq that we implemented because users forgot to filter their variants. Strandbias was one of them, but I do understand that this might not work as intended for capture data. Currently there is no easy workaround. You will have to call `lofreq call` with ` --no-default-filter` and then it's best to filter with `lofreq filter --no-defaults` and filter on quality with either `-B` (hard filtering) or `-b` (multiple testing correction using the number of tests reported by `call`)

Hope this helps
Andreas

**Comment by andreas-wilm** [comment]
Note, the value you see is the highest SB value possible and it is correctly calculated :)
