### ISSUE TITLE
GLIBC problem during installation

### ISSUE THREAD

**Issue by sleyn** [CSB5/lofreq#96]
Hi again. I've solved this problem, but just to let you know.

I failed to install lofreq 2.1.5 through conda or use pre-compiled binaries. The problem seems that on our lab CentOS server have GLIBC 2.17, but LoFreq expects 2.23.

The precompiled binaries produced and error `lofreq: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by lofreq)`. Conda installation also failed while testing GLIBC.

Compiling from the source seems work - my test BAM file was processed successfully.

**Comment by andreas-wilm** [comment]
Hi Semion, yes the precompiled binaries have some remaining dependencies and GLIBC is for sure one of them. My understanding is that the conda installation should work though. You might want to consider filing a bug there or at least ask them. Compilation from source should always work. And since it does I'm closing this for now.
